### ISSUE TITLE
Crash on start with MorePlanets 1.12.2-2.2.3-GC280

### ISSUE THREAD

**Issue by RassTass11** [SteveKunG/MorePlanets#144]
When i updated to the new More plantes my game crash on the start, i have mixinbooter 4.2 and SteveKunG´s lib 1.12.2-1.2.0

This is my crashreport

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinBooter (!mixinbooter-4.2.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.0.18.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.2.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 7/5/22 1:58 PM
Description: Initializing game

java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlockWithInventory: method <init>()V not found
	at fr.militario.spacex.tiles.TileEntityOxygenLoader.<init>(TileEntityOxygenLoader.java:54)
	at fr.militario.spacex.blocks.BlockOxygenLoader.createTileEntity(BlockOxygenLoader.java:55)
	at fr.militario.spacex.items.ItemBlockDesc.func_77624_a(ItemBlockDesc.java:86)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.lang.Iterable.forEach(Unknown Source)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at fr.militario.spacex.tiles.TileEntityOxygenLoader.<init>(TileEntityOxygenLoader.java:54)
	at fr.militario.spacex.blocks.BlockOxygenLoader.createTileEntity(BlockOxygenLoader.java:55)
	at fr.militario.spacex.items.ItemBlockDesc.func_77624_a(ItemBlockDesc.java:86)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.lang.Iterable.forEach(Unknown Source)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_333, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 236387480 bytes (225 MB) / 870318080 bytes (830 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1152m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version      | Source                                        | Signature                                |
	|:----- |:------------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2       | minecraft.jar                                 | None                                     |
	| LCH   | mcp                 | 9.42         | minecraft.jar                                 | None                                     |
	| LCH   | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2860-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2860 | forge-1.12.2-14.23.5.2860-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore       |              | minecraft.jar                                 | None                                     |
	| LCH   | mixinbooter         | 4.2          | minecraft.jar                                 | None                                     |
	| LCH   | galacticraftcore    | 4.0.2.280    | GalacticraftCore-1.12.2-4.0.2.280.jar         | None                                     |
	| LCH   | galacticraftplanets | 4.0.2.280    | Galacticraft-Planets-1.12.2-4.0.2.280.jar     | None                                     |
	| LCH   | asmodeuscore        | 0.0.30       | AsmodeusCore-1.12.2-0.0.30.jar                | None                                     |
	| LCH   | codechickenlib      | 3.2.3.358    | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | galaxyspace         | 2.0.18       | GalaxySpace-1.12.2-2.0.18.jar                 | None                                     |
	| LCH   | jei                 | 4.16.1.301   | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCH   | stevekung's_lib     | 1.2.0        | SteveKunG's-Lib-1.12.2-1.2.0.jar              | None                                     |
	| LCH   | moreplanets         | 2.2.2        | More-Planets-1.12.2-2.2.2-GC280.jar           | None                                     |
	| LCH   | nei                 | 2.4.3        | NotEnoughItems-1.12.2-2.4.3.245-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | spacecraftx         | 1.0.35       | spacecraftx-1.12.2-1.0.35.jar                 | None                                     |
	| LCH   | zollerngalaxy       | 2.0.44       | ZollernGalaxy-1.12.2-2.0.44.jar               | None                                     |

	Loaded coremods (and transformers): 
MixinBooter (!mixinbooter-4.2.jar)
  
GSHooksLoader (GalaxySpace-1.12.2-2.0.18.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.2.0.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 472.98' Renderer: 'NVIDIA GeForce GT 640/PCIe/SSE2'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GT 640/PCIe/SSE2 GL version 4.6.0 NVIDIA 472.98, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Español (España)
	Profiler Position: N/A (disabled)
	CPU: 16x Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz

**Comment by SteveKunG** [comment]
You are using an old Galacticraft, Download build 284 from here
https://www.curseforge.com/minecraft/mc-mods/galacticraft-legacy/files/3648807

**Comment by RassTass11** [comment]
Thanks, so i replace the mic doodle core, galacticraft planets and galacticraft core?

**Comment by SteveKunG** [comment]
Yep, delete 3 of them.

**Comment by RassTass11** [comment]
Thanks
