### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by xANoyU** [SteveKunG/MorePlanets#153]
https://paste.ubuntu.com/p/nKvcPtqWN6/

please help me, server crash when a player join the moreplanets DIM

**Comment by SteveKunG** [comment]
Did you have a full log? I need to see what caused the actual real issue.

**Comment by xANoyU** [comment]
> 你有完整的日志吗？我需要看看是什么导致了实际的问题。



> Did you have a full log? I need to see what caused the actual real issue.
[debug-3.log.gz](https://github.com/SteveKunG/MorePlanets/files/9316999/debug-3.log.gz)
😙

**Comment by SteveKunG** [comment]
Not MP issue, log shown PlaceholderAPI stacktrace.

```
9:18:42] [Spigot Watchdog Thread/ERROR] [Minecraft]: Could not pass event PluginDisableEvent to PlaceholderAPI v2.11.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:69) ~[EventExecutor$2.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:346) [JavaPluginLoader.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [SimplePluginManager.class:git-CatServer-1.12.2-6eb82ffe]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:405) [CraftServer.class:git-CatServer-1.12.2-6eb82ffe]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:525) [MinecraftServer.class:?]
	at org.spigotmc.RestartCommand.restart(RestartCommand.java:123) [RestartCommand.class:git-CatServer-1.12.2-6eb82ffe]
	at org.spigotmc.RestartCommand.restart(RestartCommand.java:42) [RestartCommand.class:git-CatServer-1.12.2-6eb82ffe]
	at org.spigotmc.WatchdogThread.run(WatchdogThread.java:93) [WatchdogThread.class:git-CatServer-1.12.2-6eb82ffe]
Caused by: java.lang.NullPointerException
	at moe.feo.bbstoper.PAPIExpansion.getIdentifier(PAPIExpansion.java:39) ~[?:?]
	at me.clip.placeholderapi.expansion.PlaceholderExpansion.equals(PlaceholderExpansion.java:385) ~[?:?]
	at com.google.common.collect.ImmutableSet.construct(ImmutableSet.java:185) ~[guava-21.0.jar:?]
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:267) ~[guava-21.0.jar:?]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.getExpansions(LocalExpansionManager.java:118) ~[?:?]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.onPluginDisable(LocalExpansionManager.java:453) ~[?:?]
	at catserver.server.executor.asm.generated.GeneratedEventExecutor56.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) ~[EventExecutor$2.class:git-CatServer-1.12.2-6eb82ffe]
	... 11 more
```
