### ISSUE TITLE
[Old Version] Dark Asteroids Crash issue with SkylightMap (Important!)

### ISSUE THREAD

**Issue by MJRLegends** [SteveKunG/MorePlanets#16]
Seems this crash was reported before #8 but i have more information for you on the issue..

**Crash log with Thermos (From my own personal servers):** http://pastebin.com/r1eF5sc5
**Crash log with Forge only (From https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/646):** http://pastebin.com/WyUXZEQ7

The problem seems to be line 880 of ChunkProviderDarkAsteroids.class

In v1.3.5 and v1.3.6 (Crash logs above use V1.3.5)
The line looks like this 
`chunk.func_150807_a(x - 1, y & 0xF, z, DarkAsteroidsBlocks.dark_air, 15 - count);` **Note: IS A DECOMPILED VERSION**

In v1.3.4 and below
The line looks like this 
`chunk.func_150807_a(x - 1, y & 0x5, z, DarkAsteroidsBlocks.dark_air, 5 - count);` **Note: IS A DECOMPILED VERSION**

**Changes between the two above:**
y & 0xF and y & 0x5
15 - count and 5 - count

**Seems the issue is only 1.3.5 and higher so the issue must be the changes above and changing them back should fix......**

If you need anymore help or information let me know

**Comment by SteveKunG** [comment]
I didn't getting crash in my dev workspace. Not sure why. :(

`chunk.func_150807_a(x - 1, y & 15, z, DarkAsteroidsBlocks.dark_air, 15 - count);`

This is correct code that I fixed this issue.

**Comment by MJRLegends** [comment]
Yeah to me it seems like its trying to generate outside of loaded/generated chunks

**Comment by SteveKunG** [comment]
You should delete Dark Asteroids region folder and re-generate map again.

**Comment by MJRLegends** [comment]
I cant test this as it would mean players would lose bases (items and blocks)...

**Comment by FoxAhead** [comment]
I do confirm crash with recursive chunk generation. I had crash in my quest world and repeated crash in clean creative test world. Using modpack Space Astronomy. Deleting Dark Asteroids region doesn't help. Crash could happen immediately on loading dimension or after flying some distance away from landing spot. I believe it has something with chunk generation which ends with endless recursion.
Crash-logs look the same as above. Just with different chunk coordinates.
MultiMC shows additional warnings before crashing:
`[19:57:41] [Server thread/WARN]: ****************************************
[19:57:41] [Server thread/WARN]: * There is an attempt to load a chunk (-97,-10) in dimension -2554 that is already being loaded. This will cause weird chunk breakages.
[19:57:41] [Server thread/WARN]: *  at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:154)
[19:57:41] [Server thread/WARN]: *  at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
[19:57:41] [Server thread/WARN]: *  at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[19:57:41] [Server thread/WARN]: *  at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
[19:57:41] [Server thread/WARN]: *  at net.minecraft.world.World.func_72964_e(World.java:419)
[19:57:41] [Server thread/WARN]: *  at net.minecraft.world.World.func_147475_p(World.java:2608)...
[19:57:41] [Server thread/WARN]: ****************************************
[19:57:41] [Server thread/WARN]: ****************************************
[19:57:41] [Server thread/WARN]: * There is an attempt to load a chunk (-97,-10) in dimension -2554 that is already being loaded. This will cause weird chunk breakages.
[19:57:41] [Server thread/WARN]: *  at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:154)
[19:57:41] [Server thread/WARN]: *  at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
[19:57:41] [Server thread/WARN]: *  at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[19:57:41] [Server thread/WARN]: *  at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
[19:57:41] [Server thread/WARN]: *  at net.minecraft.world.World.func_72964_e(World.java:419)
[19:57:41] [Server thread/WARN]: *  at net.minecraft.world.World.func_147475_p(World.java:2608)...
[19:57:41] [Server thread/WARN]: ****************************************
...
`

**Comment by JiFMike** [comment]
A couple of us reached the dark asteroids last night on my server and ran into this same issue. We're playing the Space Astronomy pack.  If I can provide any info to help I'll gladly provide it. Thanks for a great mod though, this has been one of the best packs we've played in while. :)

**Comment by MJRLegends** [comment]
Did you find anything else wrong or is regenerating the dimension the fix?

**Comment by SteveKunG** [comment]
Yeah, Its accidentally changed some value that should not change. I think this should be solve.
1.3.7 Will released for a moment.

**Comment by MJRLegends** [comment]
Ok, is there a ETA on v1.3.7 update?

**Comment by SteveKunG** [comment]
Right now. Please test it out if it still has an issue.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2358057-more-planets-mod-v-1-3-6-galacticraft-add-on?page=54#c1084

**Comment by MJRLegends** [comment]
Sweet thanks

**Comment by MJRLegends** [comment]
@SteveKunG umm v1.3.7 has given me this crash

Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: stevekung/mods/stevecore/CreativeTabsHelper

is stevecore needed for 1.7.10 now?

**Comment by SteveKunG** [comment]
Oops. Jar packing failed. I will reuploaded mod.

**Comment by MJRLegends** [comment]
Ok thanks :D

**Comment by SteveKunG** [comment]
http://www.mediafire.com/file/v4aa0rrhl52jt03/More-Planets-1.7.10-1.3.7.jar

Please try again.

**Comment by MJRLegends** [comment]
Perfect thanks loads fine now :D

**Comment by SteveKunG** [comment]
Please re-open if it still has an issue.
