### ISSUE TITLE
Keeps crashing when holding or overing on - Dark Energy Generator

### ISSUE THREAD

**Issue by 1Mangomaster1** [SteveKunG/MorePlanets#165]
The error seems to relate to the tooltip of the item, a division by 0 exception

Description: Rendering screen

java.lang.ArithmeticException: / by zero
    at stevekung.mods.moreplanets.planets.diona.itemblocks.ItemBlockDarkEnergyGenerator.addInformation(ItemBlockDarkEnergyGenerator.java:79)
    at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:707)
    at net.minecraft.client.gui.GuiScreen.getItemToolTip(GuiScreen.java:143)
    at net.minecraft.client.gui.GuiScreen.renderToolTip(GuiScreen.java:137)
    at net.minecraft.client.gui.inventory.GuiContainer.renderHoveredToolTip(GuiContainer.java:175)
    at de.maxhenkel.corpse.gui.GUIBase.drawScreen(GUIBase.java:31)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1124)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    
    
    I am on version 2.1.14, more specifically, playing Astroblock 2 - Lost in Space
    
    To replicate: grab a dark energy generator, place it down randomly, place dark pearls inside, pull them out a few seconds later, destroy the block and collect the item

**Comment by RimakiTaema** [comment]
I can't analyse it so can you give me full logs please

**Comment by SteveKunG** [comment]
Well, this is my wtf moment which I don't know what I'm doing with the code on that time. It should be fixed in the next release.

**Comment by oskarbukovsky** [comment]
[2024-01-26-5.log.gz](https://github.com/SteveKunG/MorePlanets/files/14068074/2024-01-26-5.log.gz)
I have same error message, crafted generator, placed, working, add the dark item, working better, mined to relocate generator, picked it up and keep crashing when i try to join our server.
