### ISSUE TITLE
Minecraft crashes when loading more planets

### ISSUE THREAD

**Issue by daan2008k** [SteveKunG/MorePlanets#171]
Minecraft keeps crashing everytime if it loads more planets, error log:
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from More Planets (moreplanets)
exit code:
-1

**Comment by RimakiTaema** [comment]
can you give me an full logs

so i will analyse it

**Comment by daan2008k** [comment]
Secondyou, here is the crash report. Is this wat you asked for?
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.8.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.8.3+274990f.jar)
  MixinBooter (!mixinbooter-8.8.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-mc1.12.2-v1.3.0.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 12/14/23 4:12 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from More Planets (moreplanets)
Caused by: java.lang.NoSuchMethodError: stevekung.mods.stevekunglib.utils.CommonRegistryUtils.registerBlock(Lnet/minecraft/block/Block;Lcom/google/common/base/Function;)V
	at stevekung.mods.moreplanets.utils.BlocksItemsRegistry.registerBlock(BlocksItemsRegistry.java:46)
	at stevekung.mods.moreplanets.init.MPBlocks.preRegister(MPBlocks.java:1452)
	at stevekung.mods.moreplanets.init.MPBlocks.init(MPBlocks.java:1118)
	at stevekung.mods.moreplanets.core.MorePlanetsMod.preInit(MorePlanetsMod.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

No Mixin Metadata is found in the Stacktrace.


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 337214376 bytes (321 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                   | Source                                    | Signature                                |
	|:----- |:------------------- |:------------------------- |:----------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2                    | minecraft.jar                             | None                                     |
	| LCH   | mcp                 | 9.42                      | minecraft.jar                             | None                                     |
	| LCH   | FML                 | 8.0.99.99                 | forge-1.12.2-14.23.5.2859.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2859              | forge-1.12.2-14.23.5.2859.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore       |                           | minecraft.jar                             | None                                     |
	| LCH   | mixinbooter         | 8.8                       | minecraft.jar                             | None                                     |
	| LCH   | opencomputers|core  | 1.8.3                     | minecraft.jar                             | None                                     |
	| LCH   | securitycraft       | v1.9.8                    | [1.12.2]+SecurityCraft+v1.9.8.jar         | None                                     |
	| LCH   | galacticraftcore    | 4.0.2.280                 | GalacticraftCore-1.12.2-4.0.2.280.jar     | None                                     |
	| LCH   | galacticraftplanets | 4.0.2.280                 | Galacticraft-Planets-1.12.2-4.0.2.280.jar | None                                     |
	| LCH   | jeid                | 1.0.3-55                  | JustEnoughIDs-1.0.3-55.jar                | None                                     |
	| LCH   | stevekung's_lib     | 1.3.0                     | SteveKunG's-Lib-mc1.12.2-v1.3.0.jar       | None                                     |
	| LCE   | moreplanets         | 2.2.2                     | More-Planets-1.12.2-2.2.2-GC280.jar       | None                                     |
	| LC    | hbm                 | NTM-Extended-1.12.2-1.9.6 | NTM-Extended-1.12.2-1.9.6.jar             | None                                     |
	| LC    | opencomputers       | 1.8.3                     | OpenComputers-MC1.12.2-1.8.3+274990f.jar  | None                                     |
	| LC    | worldedit           | 6.1.8                     | worldedit-forge-mc1.12-6.1.8-dist.jar     | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.8.jar)
  
JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  org.dimdev.jeid.JEIDTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.8.3+274990f.jar)
  li.cil.oc.common.asm.ClassTransformer
MixinBooter (!mixinbooter-8.8.jar)
  
SteveKunGLibPlugin (SteveKunG's-Lib-mc1.12.2-v1.3.0.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'

**Comment by RimakiTaema** [comment]
i cant analyse it can you give me an crashlog files or smth

**Comment by daan2008k** [comment]
This is the file, is this what you asked for?
[crash-2023-12-16_12.18.39-client.txt](https://github.com/SteveKunG/MorePlanets/files/13692379/crash-2023-12-16_12.18.39-client.txt)

**Comment by RimakiTaema** [comment]
okay i found an root cause it my MPblocks registry java one so wait until StevekunG come tho

**Comment by daan2008k** [comment]
Thanks!

**Comment by SteveKunG** [comment]
Hey! You should use More Planets 2.3.2 or above to play. Below that version is discontinued.
