### ISSUE TITLE
Server, all dark energy stuff crashing the server

### ISSUE THREAD

**Issue by HoneyFun** [SteveKunG/MorePlanets#48]
I have my own private modded server. I have been playing all around with dark energy recievers, and when it finally reached 100%, it played the explosion sound, and then I was kicked off the server. So I restarted the server, could find no dark energy core anywhere, though it has said "Dark energy core created," so I got one from the creative tab. I then threw an item in it and it crashed the server again, both times the same exception. Here is one of their crash reports, as they are all the same.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.1.7.jar)
  MtqFixPlugin (mtqfix-1.12.2-1.1.0.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 9/18/18 5:37 PM
Description: Ticking block entity

java.lang.NoClassDefFoundError: net/minecraftforge/fml/client/CustomModLoadingErrorDisplayException
	at stevekung.mods.moreplanets.tileentity.TileEntityDarkEnergyReceiver.func_73660_a(TileEntityDarkEnergyReceiver.java:340)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.client.CustomModLoadingErrorDisplayException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@430fa4ef from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 10 more
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraftforge/fml/client/CustomModLoadingErrorDisplayException for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at stevekung.mods.moreplanets.tileentity.TileEntityDarkEnergyReceiver.func_73660_a(TileEntityDarkEnergyReceiver.java:340)

-- Block entity being ticked --
Details:
	Name: minecraft:dark_energy_receiver // stevekung.mods.moreplanets.tileentity.TileEntityDarkEnergyReceiver
	Block type: ID #1404 (tile.dark_energy_receiver // stevekung.mods.moreplanets.blocks.BlockDarkEnergyReceiver)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-461,70,2198), Chunk: (at 3,4,6 in -29,137; contains blocks -464,0,2192 to -449,255,2207), Region: (-1,4; contains chunks -32,128 to -1,159, blocks -512,0,2048 to -1,255,2559)
	Actual block type: ID #1404 (tile.dark_energy_receiver // stevekung.mods.moreplanets.blocks.BlockDarkEnergyReceiver)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: worldOfLightningTown
	All players: 1 total; [GCEntityPlayerMP['LyghtningWither'/293569, l='worldOfLightningTown', x=-460.48, y=70.70, z=2198.65]]
	Chunk stats: ServerChunkCache: 695 Drop: 0
	Level seed: 5517215750442302603
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-513,77,2203), Chunk: (at 15,4,11 in -33,137; contains blocks -528,0,2192 to -513,255,2207), Region: (-2,4; contains chunks -64,128 to -33,159, blocks -1024,0,2048 to -513,255,2559)
	Level time: 154649506 game time, 7666 day time
	Level dimension: 512
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 103684 (now: false), thunder time: 3807 (now: true)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 2.6.32-696.18.7.el6.x86_64
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 598657992 bytes (570 MB) / 2130051072 bytes (2031 MB) up to 2130051072 bytes (2031 MB)
	JVM Flags: 10 total; -Xmx2048M -Xms2048M -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalMode -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts -XX:+CMSClassUnloadingEnabled -XX:MaxMetaspaceSize=256M
	IntCache: cache: 0, tcache: 0, allocated: 14, tallocated: 98
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 32 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version          | Source                                    | Signature                                |
	|:--------- |:------------------- |:---------------- |:----------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2           | minecraft.jar                             | None                                     |
	| UCHIJAAAA | mcp                 | 9.42             | minecraft.jar                             | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99        | forge-1.12.2-14.23.4.2705-universal.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.4.2705     | forge-1.12.2-14.23.4.2705-universal.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | micdoodlecore       |                  | minecraft.jar                             | None                                     |
	| UCHIJAAAA | securitycraft       | v1.8.4.1         | [1.12.x]+SecurityCraft+v1.8.4.1.jar       | None                                     |
	| UCHIJAAAA | adminweapons        | 3.4              | Admin-Weapons-1.12.jar                    | None                                     |
	| UCHIJAAAA | buildcraftlib       | 7.99.17          | buildcraft-7.99.17.jar                    | None                                     |
	| UCHIJAAAA | buildcraftcore      | 7.99.17          | buildcraft-7.99.17.jar                    | None                                     |
	| UCHIJAAAA | buildcraftbuilders  | 7.99.17          | buildcraft-7.99.17.jar                    | None                                     |
	| UCHIJAAAA | buildcraftenergy    | 7.99.17          | buildcraft-7.99.17.jar                    | None                                     |
	| UCHIJAAAA | buildcraftfactory   | 7.99.17          | buildcraft-7.99.17.jar                    | None                                     |
	| UCHIJAAAA | buildcraftrobotics  | 7.99.17          | buildcraft-7.99.17.jar                    | None                                     |
	| UCHIJAAAA | buildcrafttransport | 7.99.17          | buildcraft-7.99.17.jar                    | None                                     |
	| UCHIJAAAA | buildcraftsilicon   | 7.99.17          | buildcraft-7.99.17.jar                    | None                                     |
	| UCHIJAAAA | cfm                 | 4.1.5            | cfm-4.1.5-mc1.12.jar                      | None                                     |
	| UCHIJAAAA | chisel              | MC1.12-0.0.14.18 | Chisel-MC1.12-0.0.14.18.jar               | None                                     |
	| UCHIJAAAA | redstoneflux        | 2.0.1            | RedstoneFlux-1.12-2.0.1.2-universal.jar   | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | cofhcore            | 4.3.10           | CoFHCore-1.12.2-4.3.10.5-universal.jar    | None                                     |
	| UCHIJAAAA | cofhworld           | 1.1.1            | CoFHWorld-1.12.2-1.1.1.12-universal.jar   | None                                     |
	| UCHIJAAAA | computercraft       | 1.80pr1          | ComputerCraft-Mod-1.12.1.jar              | None                                     |
	| UCHIJAAAA | galacticraftcore    | 4.0.1.181        | GalacticraftCore-1.12.2-4.0.1.181.jar     | None                                     |
	| UCHIJAAAA | galacticraftplanets | 4.0.1.181        | Galacticraft-Planets-1.12.2-4.0.1.181.jar | None                                     |
	| UCHIJAAAA | hm                  | 1.2              | HoneyFun's Mod - 1.3b1 @ 1.12.2.jar       | None                                     |
	| UCHIJAAAA | malisiscore         | 1.12.2-6.1.7     | malisiscore-1.12.2-6.1.7.jar              | None                                     |
	| UCHIJAAAA | malisisblocks       | 1.12.2-6.1.0     | malisisblocks-1.12.2-6.1.0.jar            | None                                     |
	| UCHIJAAAA | malisisdoors        | 1.12.2-7.1.1     | malisisdoors-1.12.2-7.1.1.jar             | None                                     |
	| UCHIJAAAA | moreplanets         | 2.0.16           | More-Planets-1.12.2-2.0.16-GC181.jar      | b3468b224a74e296555ad7efeb35f482e6f445de |
	| UCHIJAAAA | harvestcraft        | 1.12.2t          | Pam'sHarvestCraft1.12.2.jar               | None                                     |
	| UCHIJAAAA | stevekung's_lib     | 1.0.3            | SteveKunGs-Lib-1.12.2-1.0.3.jar           | b3468b224a74e296555ad7efeb35f482e6f445de |
	| UCHIJAAAA | worldedit           | 6.1.8            | worldedit-forge-mc1.12-6.1.8-dist.jar     | None                                     |
	| UD        | mtqfix              | 1.1.0            | minecraft.jar                             | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.1.7.jar)
  
MtqFixPlugin (mtqfix-1.12.2-1.1.0.jar)
  jmn.mods.mtqfix.AsmTransformer
	Profiler Position: N/A (disabled)
	Player Count: 2 / 35; [GCEntityPlayerMP['LyghtningWither'/293569, l='worldOfLightningTown', x=-460.48, y=70.70, z=2198.65], GCEntityPlayerMP['GummiRevolution'/336102, l='worldOfLightningTown', x=8.75, y=67.00, z=26.64]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by HoneyFun** [comment]
This is not fixed. I tried the beta version, and it was still crashing. I also tried the release that was made the same day of the beta release, and it also crashed.

**Comment by HoneyFun** [comment]
This is on a server. It is using a class that is not in the server JAR.

**Comment by HoneyFun** [comment]
It happens when the dark energy receiver is finished and has created the dark energy core.

**Comment by HoneyFun** [comment]
This is server only. I tested it on a singleplayer world and it worked fine.
