### ISSUE TITLE
1.8.9 crash with galactical craft and more planets

### ISSUE THREAD

**Issue by iHoriZonT** [SteveKunG/MorePlanets#51]
I tryied use 

GalacticraftCore-1.8.9-4.0.1.181.jar
Galacticraft-Planets-1.8.9-4.0.1.181.jar
MicdoodleCore-1.8.9-4.0.1.181.jar

with 

More-Planets-1.8.9-2.0.7-GC119

But:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.1.181.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 07/11/18 09:51
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.AbstractMethodError
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:325)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:205)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AbstractMethodError
	at micdoodle8.mods.galacticraft.api.galaxies.CelestialBody.getSurfaceBlocks(CelestialBody.java:356)
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.postInit(GalacticraftCore.java:369)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2284609368 bytes (2178 MB) / 2512388096 bytes (2396 MB) up to 2512388096 bytes (2396 MB)
	JVM Flags: 2 total; -Xms2500M -Xmx2500M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9-universal.jar) 
	UCHIJ	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9-universal.jar) 
	UCHIJ	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIE	GalacticraftCore{4.0.1.181} [Galacticraft Core] (GalacticraftCore-1.8.9-4.0.1.181.jar) 
	UCHIE	GalacticraftPlanets{4.0.1.181} [Galacticraft Planets] (Galacticraft-Planets-1.8.9-4.0.1.181.jar) 
	UCHIJ	mjrlegendslib{1.8.9-1.1.1} [MJRLegendsLib] (MJRLegendsLib-1.8.9-1.1.1.jar) 
	UCHIE	moreplanets{2.0.7} [More Planets] (More-Planets-1.8.9-2.0.7-GC119.jar) 
	UCHIJ	mw{1.10.3} [Modern Warfare] (mw-1.10.3_mc1.8.9.jar) 
	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.8.9-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by iHoriZonT** [comment]
same problem with extra planets

**Comment by SteveKunG** [comment]
Sorry, I don't support 1.8.9 anymore.
