### ISSUE TITLE
Crash report upon startup 1.12.2

### ISSUE THREAD

**Issue by Kindomfighter** [SteveKunG/MorePlanets#97]
upon started on phase 6 of loading all the mods on forge I got this
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock: method <init>()V not found
Exit Code: -1

This is the full crash log
--- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.7-core.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 9/4/20 9:45 AM
Description: Initializing game

java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock: method <init>()V not found
	at galaxyspace.systems.SolarSystem.planets.overworld.tile.TileEntityAssembler.<init>(TileEntityAssembler.java:50)
	at galaxyspace.systems.SolarSystem.planets.overworld.blocks.machines.BlockAssembler.func_149915_a(BlockAssembler.java:78)
	at net.minecraft.block.Block.createTileEntity(Block.java:1274)
	at galaxyspace.core.prefab.items.GSItemBlockDesc.func_77624_a(GSItemBlockDesc.java:82)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$647/485248560.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$650/1449764345.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraftforge.fml.client.FMLClientHandler.reloadSearchTrees(FMLClientHandler.java:1086)
	at net.minecraftforge.fml.common.FMLCommonHandler.reloadSearchTrees(FMLCommonHandler.java:778)
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:589)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:916)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:259)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at galaxyspace.systems.SolarSystem.planets.overworld.tile.TileEntityAssembler.<init>(TileEntityAssembler.java:50)
	at galaxyspace.systems.SolarSystem.planets.overworld.blocks.machines.BlockAssembler.func_149915_a(BlockAssembler.java:78)
	at net.minecraft.block.Block.createTileEntity(Block.java:1274)
	at galaxyspace.core.prefab.items.GSItemBlockDesc.func_77624_a(GSItemBlockDesc.java:82)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$647/485248560.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$650/1449764345.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraftforge.fml.client.FMLClientHandler.reloadSearchTrees(FMLClientHandler.java:1086)
	at net.minecraftforge.fml.common.FMLCommonHandler.reloadSearchTrees(FMLCommonHandler.java:778)
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:589)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:916)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:259)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 495668496 bytes (472 MB) / 1543503872 bytes (1472 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 26 mods loaded, 26 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version        | Source                               | Signature                                |
	|:------ |:------------------- |:-------------- |:------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2         | minecraft.jar                        | None                                     |
	| LCHIJA | mcp                 | 9.42           | minecraft.jar                        | None                                     |
	| LCHIJA | FML                 | 8.0.99.99      | forge-1.12.2-14.23.5.2854.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2854   | forge-1.12.2-14.23.5.2854.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       |                | minecraft.jar                        | None                                     |
	| LCHIJA | foamfixcore         | 7.7.4          | minecraft.jar                        | None                                     |
	| LCHIJA | voxelmap            | 1.9.10         | VoxelMap-Mod-1.12.2.jar              | None                                     |
	| LCHIJA | aether_legacy       | 1.4.4          | Aether-Legacy-Mod-1.12.2.jar         | None                                     |
	| LCHIJA | mantle              | 1.12-1.3.3.55  | Mantle-Mod-1.12.2.jar                | None                                     |
	| LCHIJA | twilightforest      | 3.9.888        | Twilight-Forest-Mod-1.12.2.jar       | None                                     |
	| LCHIJA | tconstruct          | 1.12-2.8.1.49  | Tinkers-Construct-Mod-1.12.1.jar     | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.2.220      | Galacticraft-Mod-1.12.2.jar          | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.220      | Galacticraft-Planets-Mod-1.12.2.jar  | None                                     |
	| LCHIJA | asmodeuscore        | 0.0.6          | AsmodeusCore-1.12.2.jar              | None                                     |
	| LCHIJA | chunkanimator       | 1.2            | ChunkAnimator-MC1.12-1.2.jar         | None                                     |
	| LCHIJA | dimdoors            | 3.0.9+287      | Dimensional-Doors-Mod-1.12.2.jar     | None                                     |
	| LCHIJA | foamfix             | 0.10.10-1.12.2 | foamfix-0.10.10-1.12.2.jar           | None                                     |
	| LCHIJA | galaxyspace         | 2.0.6          | Galaxy-Space-Mod-1.12.2.jar          | None                                     |
	| LCHIJA | llibrary            | 1.7.19         | llibrary-1.7.19-1.12.2.jar           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire          | 1.9.1          | iceandfire-1.9.1-1.12.2.jar          | None                                     |
	| LCHIJA | lost_aether         | 0.1.2          | lost_aether-content-1.12.2-0.1.2.jar | None                                     |
	| LCHIJA | roguelike           | 1.8.0          | RoguelikeDungeons-1.12.2-1.8.0.jar   | None                                     |
	| LCHIJA | sekcphysics         | 0.1.0          | sekcphysics-0.1.0.jar                | None                                     |
	| LCHIJA | surge               | 2.0.77         | Surge-1.12.2-2.0.77.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | densemetals         | 2.0.0          | DenseMetals-1.12.2-2.0.0.30.jar      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | thebetweenlands     | 3.4.7          | TheBetweenlands-3.4.7-universal.jar  | 38067d6878811efb38b6a045521cfd80b9b60b38 |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.7-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 442.19' Renderer: 'GeForce GTX 950/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 950/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.19, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 20
	Mipmaps: 2
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 442.19
	OpenGlRenderer: GeForce GTX 950/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by SteveKunG** [comment]
That's from GalaxySpace.
`at galaxyspace.systems.SolarSystem.planets.overworld.tile.TileEntityAssembler.(TileEntityAssembler.java:50)`
